apiVersion: v1
kind: Service
metadata:
  name: testfest-service
spec:
  selector:
    app: testfest-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort # Required for ALB Ingress Controller
